services:
    laravel:
        build:
            context: './'
            dockerfile: Dockerfile
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
            - '443:443/udp'
        environment:
            LARAVEL_SAIL: 1
        command: php artisan octane:start --host=localhost --port=443 --admin-port=2019 --https --http-redirect --watch
        volumes:
            - '.:/app'
        depends_on:
            - mysql
            - redis
            - mailpit
    mysql:
        image: 'mariadb:12.1.2'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS:-}'
        volumes:
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        command: redis-server --appendonly no --save 0 --maxmemory 50M --maxmemory-policy lru-volatile
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
networks:
    sail:
        driver: bridge
